# CMD
install:
	bun install

dev:
	bun dev

build:
	bun build

preview:
	bun preview

lint:
	bun lint

format:
	bun check

clean:
	rm -rf node_modules dist

# SETUP
setup: clean install
	bunx biome init