[project]
name = "ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asgiref>=3.11.1",
    "celery>=5.6.2",
    "crawl4ai>=0.8.0",
    "fastapi>=0.129.0",
    "litellm>=1.81.13",
    "openai>=2.21.0",
    "playwright>=1.58.0",
    "pydantic>=2.12.5",
    "pydantic-settings>=2.13.0",
    "redis>=7.2.0",
    "scalar-fastapi>=1.6.2",
    "uvicorn[standard]>=0.40.0",
]
